name: webview_universal
description: Show a webview window on your flutter cross platform android, ios, linux, macos, web, windows.
version: 0.0.5

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
  
environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  universal_io: ^2.2.0
  webview_flutter: ^4.0.6
  webview_flutter_android: ^3.4.2
  webview_flutter_web: ^0.2.2+1
  webview_flutter_wkwebview: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
 
flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WebviewUniversalPlugin
      windows:
        pluginClass: WebviewUniversalPlugin
      linux:
        pluginClass: WebviewUniversalPlugin
